### PR TITLE
pack compressed VSTS package with CLI code for better install performance

### PR DESCRIPTION
**Pull request by gauravsaralMs**
Please make sure the code is following contribution guidelines in CONTRIBUTING.md

 - [ ] : This PR has a corresponding issue open in the Repository.
 - [ ] : Approach is signed off on the issue.

### CODE REVIEW

**Comment by atbagga** [comment]
Why name it vstsCompressed? vsts is sufficient I guess.

**Comment by gauravsaralMs** [comment]
> Why name it vstsCompressed? vsts is sufficient I guess.

Just to make someone does not copies the whole VSTS folder from python api repo without compressing

**Comment by atbagga** [comment]
> > Why name it vstsCompressed? vsts is sufficient I guess.
> 
> Just to make sure someone does not copies the whole VSTS folder from python api repo without compressing

@gauravsaralMs @ishitam8  This doesn't follow the standard of all lowercase names. Should it be vsts_compressed ?
I would have been fine with vsts also I don't think someone will replace that with original vsts package files blindly.

**Comment by gauravsaralMs** [comment]
> > > Why name it vstsCompressed? vsts is sufficient I guess.
> > 
> > 
> > Just to make sure someone does not copies the whole VSTS folder from python api repo without compressing
> 
> @gauravsaralMs @ishitam8 This doesn't follow the standard of all lowercase names. Should it be vsts_compressed ?
> I would have been fine with vsts also I don't think someone will replace that with original vsts package files blindly.

@atbagga 
nice catch, feel free to change/fix or open an issue but given that this is just a temp thing till we get new optimized DevOps python client package I am not very much in favor of putting time on this again.

**Pull request merged**
