### PR TITLE
Add methods to manage Git pushes

### PR DESCRIPTION
**Pull request by vbossica**
Add methods to create Git pushes:

- add
- update
- delete
- move

Work related to the issue #122

### CODE REVIEW

**Comment by geverghe** [comment]
@vbossica - could you include the details of the commands that you are envisioning?

**Comment by atbagga** [comment]
@vbossica Closing the older PRs on VSTS-CLI code. Feel free to get the corresponding workitems assigned to yourself when you work on it with the new codebase.

**Comment by kamil-mrzyglod** [comment]
Hey there, is there any followup on this feature? As far as I'm concerned, there're no methods on CLI, which allows you to push files for now :( Or am I missing something?

**Comment by atbagga** [comment]
@kamil-mrzyglod  Since users can achieve this via git client this has not been prioritized. 
If you still feel the need of these commands please vote on the related issue (via mojis or comment explaining the need of this command) https://github.com/Azure/azure-devops-cli-extension/pull/121 so this can be prioritized.

**Pull request closed without merging**
