### PR TITLE
Add, remove and show relations of a work item

### PR DESCRIPTION
**Pull request by vbossica**
Add commands to add, remove and show relations of a work item:

Add `--expand` option so show the work item's relations:

    vsts work item show --id [ID] --expand relations

To define the parent of a work item:

    vsts work item create ... --parent [ID]

To add a relation:

    vsts work item relation add --id [ID] --relations duplicate=[ID1,ID2]

To show the relations:

    vsts work item relation show --id [ID]
    
To remove a relation:

    vsts work item relation remove --id [ID] --indexes=[IDX1,IDX2]

The indexes of the relations can be seen with `--output table`

This addresses one of the requests of #93

### CODE REVIEW

**Comment by peteg18** [comment]
Thanks!

**Comment by VelinGeorgiev** [comment]
Hi, any progress on that?

**Comment by tedchamb** [comment]
@VelinGeorgiev, there is going to be a large round of investment in the cli coming soon. These PRs are on the list.

**Comment by VelinGeorgiev** [comment]
Thanks for the update @tedchamb! Looking forward for that new update.

**Comment by jboulter11** [comment]
@tedchamb any update on eta on this?  Would love to see this functionality enabled.

**Comment by tedchamb** [comment]
@geverghe is now managing the backlog, and can give you a better idea when this may be available.

**Comment by gergoszucs** [comment]
@vbossica @geverghe Do you guys have any plans to merge these changes in the near future?

**Comment by geverghe** [comment]
@jboulter11, @VelinGeorgiev, @peteg18, @gergoszucs, @vbossica  - Apologies for the delayed response. We have been busy porting the existing VSTS CLI as Azure DevOps extension to Azure CLI. 

@vbossica a few recommendation to the command structure
1. The commands need to be altered to be inline with the new command groups. Therefore, `vsts work item` would be `az boards work-item show`

_Add --expand option so show the work item's relations:
vsts work item show --id [ID] --expand relations_

2. I see that you are using --expand relations as a switch to include the relations details in the json output. Further investigation using the [work item api documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20item?view=azure-devops-rest-5.0) and a few tests indicate that expand=links/fields/none give the same output, with expand=relations/all including the relation details. Ideally, show should be rendering the complete json and therefore by default show have expand=all implemented. 
3. To view just the relation details, the recommendation would be to use JMES Path query to extract the relevant details and output it in the desired format.

_To define the parent of a work item:
vsts work item create ... --parent [ID]_
 4. This command look too specific to a scenario.  There are about 18 different supported relation types as per the [documentation example](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20relation%20types/list?view=azure-devops-rest-5.0). Although parenting might be the predominant scenario, our commanding structure should be able to scale to multiple relation type needs. 
My recommendation would be to follow the following structure:
az boards work-item create --relation parent=ID1,ID2,ID3 child=ID4, ID5
This way we can scale to linking work items across different relation types.

Work Item relationship management
_To add a relation:
vsts work item relation add --id [ID] --relations duplicate=[ID1,ID2]
To show the relations:
vsts work item relation show --id [ID]
To remove a relation:
vsts work item relation remove --id [ID] --indexes=[IDX1,IDX2]_

5. Above make sense. Only recommendation would be to move it to az boards work-item command group;
Commands will be
`az boards work-item relation add` 
`az boards work-item relation show`
`az boards work-item relation remove`

_The indexes of the relations can be seen with --output table_
I didn't quite get what you meant by this one. Could you elaborate on this?

**Comment by atbagga** [comment]
@vbossica Closing the older PRs on VSTS-CLI code. Feel free to get the corresponding workitems assigned to yourself when you work on it with the new code base.

**Comment by f00-beerd** [comment]
If folks are using DevOps Server 2019, how can they programmatically get the parent workitem ID?

**Comment by atbagga** [comment]
@f00-beerd 
You can use the command - ```az boards work-item relation show```
Documentation [here](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/boards/work-item/relation?view=azure-cli-latest#ext-azure-devops-az-boards-work-item-relation-show).

This is how the sample output will look like.. 
```
PS D:\azure-devops> az boards work-item relation show --id 5
Relation Type    Url
---------------  -----------------------------------------------------------------------------------------
Child            <Organization Url>/_apis/wit/workItems/18

PS D:\azure-devops> az boards work-item relation show --id 12
Relation Type    Url
---------------  ----------------------------------------------------------------------------------------
Parent           <Organization Url>/_apis/wit/workItems/6
```

**Pull request closed without merging**
